DROP TABLE IF EXISTS days;

CREATE TABLE days (
    id SERIAL PRIMARY KEY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    text1 TEXT NOT NULL,
    text2 TEXT NOT NULL,
    text3 TEXT NOT NULL
);